/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package org.example;

public class MenuPage {
    public String getGreeting() {
        return "Hello World!";
    }

    public static void main(String[] args) {
        System.out.println(new MenuPage().getGreeting());
    }
}
