[versions]
guava = "32.1.3-jre"
junit-jupiter = "5.10.0"

[libraries]
guava = { module = "com.google.guava:guava", version.ref = "guava" }
junit-jupiter = { module = "org.junit.jupiter:junit-jupiter", version.ref = "junit-jupiter" }

[plugins]
oop = "org.danilopianini.unibo-oop-gradle-plugin:1.0.11"
